# Generated by Django 4.1.7 on 2023-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth_api", "0004_alter_accesstoken_id_alter_application_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorizationcode",
            name="code",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
